#version: "3.8"
services:
  backend:
    image: app:discoveralgeria
    container_name: discoveralgeria_container
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    volumes:
      - .:/discoveralgeria
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "host.docker.internal"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
