# Generated by Django 5.0.2 on 2024-04-04 14:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_city_description_country_country_code_and_more'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.country'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.PositiveIntegerField(default=555, validators=[django.core.validators.RegexValidator(regex='^\\d{7,15}$')]),
            preserve_default=False,
        ),
    ]
