# Generated by Django 5.0.2 on 2024-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='cover_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
