# Generated by Django 5.0.2 on 2024-03-03 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.URLField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='amenitycategory',
            name='icon',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='business_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cover_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='website_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_per_night',
            field=models.BigIntegerField(),
        ),
        migrations.AlterModelTable(
            name='hotelimage',
            table='hotel_images',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='main_bed_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.bedtype'),
        ),
    ]
