# Generated by Django 5.0.2 on 2024-03-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_roomtype_cover_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('free_cancellation_days', models.IntegerField()),
                ('breakfast_included', models.BooleanField()),
                ('prepayment_required', models.BooleanField()),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy', to='hotels.roomtype')),
            ],
        ),
    ]
