# Generated by Django 5.0.2 on 2024-04-20 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_reservation_country_code_alter_reservation_country'),
        ('owners', '0004_owner_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='owners.owner'),
        ),
    ]
