# Generated by Django 5.0.2 on 2024-03-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_roomtypepolicy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomtypepolicy',
            table='room_type_policy',
        ),
    ]
