# Generated by Django 5.0.2 on 2024-03-22 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_roomtypepolicy_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Refused', 'Refused'), ('Cancelled_By_Owner', 'Cancelled By Owner'), ('Cancelled_By_Guest', 'Cancelled By Guest'), ('Completed', 'Completed'), ('Deleted_By_Admin', 'Deleted By Admin')], default='Accepted', max_length=50),
        ),
    ]
