# Generated by Django 5.0.2 on 2024-03-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_reservation_hotel_alter_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='check_out',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
