# Generated by Django 5.0.2 on 2024-04-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_reservation_chk_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
    ]
