# Generated by Django 5.0.2 on 2024-04-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_remove_reservation_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='reservedroomtype',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_room_types', to='hotels.roomtype'),
        ),
    ]
