# Generated by Django 5.0.2 on 2024-03-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_rename_end_date_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
