# Generated by Django 5.0.2 on 2024-04-27 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_country_country_code'),
        ('hotels', '0008_hotelrule_language_parkingsituation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
