# Generated by Django 5.0.2 on 2024-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_reservation_created_at_reservation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtype',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
