# Generated by Django 5.0.2 on 2024-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_bedtype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cover_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
