# Generated by Django 5.0.2 on 2024-04-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_rename_check_in_hotelrule_check_in_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_from', models.TimeField()),
                ('check_in_until', models.TimeField()),
                ('check_out_from', models.TimeField()),
                ('check_out_until', models.TimeField()),
                ('cancellation_policy', models.CharField(choices=[('No Cancellation Policy', 'No'), ('Cancellation Depends on Selected Room Type', 'Depends'), ('Fixed Cancellation Before', 'Fixed')], max_length=255)),
                ('days_before_cancellation', models.PositiveIntegerField(default=0)),
                ('prepayment_policy', models.CharField(choices=[('Required', 'Required'), ('Not Required', 'Not Required'), ('Depends on Selected Room Type', 'Depends')], max_length=255)),
            ],
            options={
                'db_table': 'hotel_rules_',
            },
        ),
        migrations.DeleteModel(
            name='HotelRule',
        ),
        migrations.AddConstraint(
            model_name='hotelrules',
            constraint=models.CheckConstraint(check=models.Q(('cancellation_policy__in', ['No Cancellation Policy', 'Cancellation Depends on Selected Room Type', 'Fixed Cancellation Before'])), name='chk_cancellation_policy'),
        ),
        migrations.AddConstraint(
            model_name='hotelrules',
            constraint=models.CheckConstraint(check=models.Q(('prepayment_policy__in', ['Required', 'Not Required', 'Depends on Selected Room Type'])), name='chk_prepayment_policy'),
        ),
    ]
