# Generated by Django 5.0.2 on 2024-04-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_hotelrules_delete_hotelrule_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelrules',
            table='hotel_rules',
        ),
    ]
