# Generated by Django 5.0.2 on 2024-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_alter_hotelrules_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parkingsituation',
            name='chk_parking_type',
        ),
        migrations.RenameField(
            model_name='parkingsituation',
            old_name='type',
            new_name='parking_type',
        ),
        migrations.AddConstraint(
            model_name='parkingsituation',
            constraint=models.CheckConstraint(check=models.Q(('parking_type__in', ['Private', 'Public'])), name='chk_parking_type'),
        ),
    ]
