# Generated by Django 5.0.2 on 2024-04-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_remove_parkingsituation_chk_parking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='parking_available',
            field=models.BooleanField(default=False),
        ),
    ]
