# Generated by Django 5.0.2 on 2024-04-28 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_hotel_parking_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrules',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='hotels.hotel'),
        ),
    ]
