# Generated by Django 5.0.2 on 2024-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_hotelrules_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Hidden', 'Hidden'), ('Deleted By Owner', 'Deleted By Owner'), ('Deleted By Admin', 'Deleted By Admin')], default='Visible', max_length=255),
        ),
    ]
