# Generated by Django 5.0.2 on 2024-04-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_country_country_code'),
        ('hotels', '0016_hotel_status'),
        ('owners', '0004_owner_birthday'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Visible', 'Hidden', 'Deleted By Owner', 'Deleted By Admin'])), name='chk_hotel_status'),
        ),
    ]
