# Generated by Django 5.0.2 on 2024-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_hotel_chk_hotel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.ImageField(null=True, upload_to='hotels/amenities/'),
        ),
        migrations.AlterField(
            model_name='amenitycategory',
            name='icon',
            field=models.ImageField(null=True, upload_to='hotels/amenities/'),
        ),
        migrations.AlterField(
            model_name='bedtype',
            name='icon',
            field=models.ImageField(null=True, upload_to='hotels/bed_types/'),
        ),
    ]
