# Generated by Django 5.0.2 on 2024-04-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_alter_amenity_icon_alter_amenitycategory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='status',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Hidden', 'Hidden'), ('Deleted By Owner', 'Deleted By Owner')], default='VISIBLE', max_length=255),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Twin', 'Twin'), ('Twin/Double', 'Twin Double'), ('Triple', 'Triple'), ('Quadruple', 'Quadruple'), ('Suite', 'Suite'), ('Family', 'Family'), ('Studio', 'Studio'), ('Apartment', 'Apartment'), ('Dormitory Room', 'Dormitory Room'), ('Bed in Dormitory', 'Bed In Dormitory')], max_length=255),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(check=models.Q(('name__in', ['Single', 'Double', 'Twin', 'Twin/Double', 'Triple', 'Quadruple', 'Suite', 'Family', 'Studio', 'Apartment', 'Dormitory Room', 'Bed in Dormitory'])), name='chk_room_type_name'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Visible', 'Hidden', 'Deleted By Owner'])), name='chk_room_type_status'),
        ),
    ]
