# Generated by Django 5.0.2 on 2024-04-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_roomtype_status_alter_roomtype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='commission',
            field=models.BigIntegerField(null=True),
        ),
    ]
