# Generated by Django 5.0.2 on 2024-05-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_remove_reservation_chk_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsituation',
            name='hotel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_situation', to='hotels.hotel'),
        ),
    ]
