# Generated by Django 5.0.2 on 2024-05-02 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_roomtypeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='bed_types',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='nb_beds',
        ),
        migrations.CreateModel(
            name='RoomTypeBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.bedtype')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='hotels.roomtype')),
            ],
            options={
                'db_table': '_room_type_beds',
                'unique_together': {('room_type', 'bed_type')},
            },
        ),
    ]
