# Generated by Django 5.0.2 on 2024-05-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_remove_roomtype_bed_types_remove_roomtype_nb_beds_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomtypebed',
            table='room_type_beds',
        ),
    ]
