# Generated by Django 5.0.2 on 2024-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_alter_roomtypebed_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number_of_guests',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
