# Generated by Django 5.0.2 on 2024-05-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_remove_room_number_of_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtypepolicy',
            name='breakfast_included',
        ),
        migrations.RemoveField(
            model_name='roomtypepolicy',
            name='free_cancellation_days',
        ),
        migrations.RemoveField(
            model_name='roomtypepolicy',
            name='prepayment_required',
        ),
        migrations.AddField(
            model_name='roomtypepolicy',
            name='cancellation_policy',
            field=models.CharField(choices=[('No Cancellation', 'No'), ('Cancellation Before', 'Before')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roomtypepolicy',
            name='days_before_cancellation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomtypepolicy',
            name='prepayment_policy',
            field=models.CharField(choices=[('Prepayment is not required', 'Not Required'), ('Prepayment is required', 'Required')], max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='roomtypepolicy',
            constraint=models.CheckConstraint(check=models.Q(('cancellation_policy__in', ['No Cancellation', 'Cancellation Before'])), name='chk_room_type_cancellation_policy'),
        ),
        migrations.AddConstraint(
            model_name='roomtypepolicy',
            constraint=models.CheckConstraint(check=models.Q(('prepayment_policy__in', ['Prepayment is not required', 'Prepayment is required'])), name='chk_room_type_prepayment_policy'),
        ),
    ]
