# Generated by Django 5.0.2 on 2024-05-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0029_roomtypepolicies_delete_roomtypepolicy_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomtypepolicies',
            table='room_type_policy',
        ),
    ]
