# Generated by Django 5.0.2 on 2024-05-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0030_alter_roomtypepolicies_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtypepolicies',
            name='room_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='hotels.roomtype'),
        ),
    ]
