# Generated by Django 5.0.2 on 2024-05-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0031_alter_roomtypepolicies_room_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomtypepolicies',
            name='chk_room_type_prepayment_policy',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roomtypepolicies',
            name='prepayment_policy',
            field=models.CharField(choices=[('Not Required', 'Not Required'), ('Required', 'Required')], max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='roomtypepolicies',
            constraint=models.CheckConstraint(check=models.Q(('prepayment_policy__in', ['Not Required', 'Required'])), name='chk_room_type_prepayment_policy'),
        ),
    ]
