# Generated by Django 5.0.2 on 2024-05-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0032_remove_roomtypepolicies_chk_room_type_prepayment_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedtype',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bedtype',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.ImageField(null=True, upload_to='accommodations/amenities/'),
        ),
        migrations.AlterField(
            model_name='amenitycategory',
            name='icon',
            field=models.ImageField(null=True, upload_to='accommodations/amenities/'),
        ),
        migrations.AlterField(
            model_name='bedtype',
            name='icon',
            field=models.ImageField(null=True, upload_to='accommodations/hotels/bed_types/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='accommodations/hotels/'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='img',
            field=models.ImageField(null=True, upload_to='accommodations/hotels/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='accommodations/hotels/'),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='image',
            field=models.ImageField(upload_to='accommodations/room_types/'),
        ),
    ]
