# Generated by Django 5.0.2 on 2024-05-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0033_bedtype_length_bedtype_width_alter_amenity_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='accommodations/room_types/'),
        ),
    ]
