# Generated by Django 5.0.2 on 2024-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0034_alter_roomtype_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedtype',
            name='icon',
            field=models.ImageField(null=True, upload_to='accommodations/bed_types/'),
        ),
    ]
