# Generated by Django 5.0.2 on 2024-05-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0036_remove_roomtypepolicies_chk_room_type_prepayment_policy_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomtypeimage',
            table='room_type_images',
        ),
    ]
