# Generated by Django 5.0.2 on 2024-05-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0037_alter_roomtypeimage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Hidden', 'Hidden'), ('Deleted', 'Deleted')], default='Visible', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Visible', 'Hidden', 'Deleted'])), name='chk_room_status'),
        ),
    ]
