# Generated by Django 5.0.2 on 2024-05-20 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0039_remove_reservation_chk_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='contact_number',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(regex='^\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(regex='^\\d{7,15}$')]),
        ),
    ]
