# Generated by Django 5.0.2 on 2024-03-09 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristicagencies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_status',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Hidden', 'Hidden'), ('Deleted', 'Deleted')], default='Visible', max_length=25),
        ),
        migrations.AddField(
            model_name='tour',
            name='touristic_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, related_name='tours', to='touristicagencies.touristicagency'),
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
