# Generated by Django 5.0.2 on 2024-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristicagencies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cover_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
