# Generated by Django 5.0.2 on 2024-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristicagencies', '0003_tour_created_at_tour_tour_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.TimeField(),
        ),
    ]
