# Generated by Django 5.0.2 on 2024-03-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_city_cover_img'),
        ('touristicagencies', '0003_tour_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicagency',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touristic_agencies', to='destinations.country'),
        ),
        migrations.AlterField(
            model_name='touristicagency',
            name='cover_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
