# Generated by Django 5.0.2 on 2024-04-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_country_country_code'),
        ('guests', '0004_alter_guest_phone'),
        ('touristicagencies', '0003_periodictourregistration_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodictourregistration',
            name='chk_tour_reg_status',
        ),
        migrations.AlterField(
            model_name='periodictourregistration',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Active', 'Active'), ('Cancelled_By_Owner', 'Cancelled By Owner'), ('Cancelled_By_Guest', 'Cancelled By Guest'), ('Completed', 'Completed'), ('Deleted_By_Admin', 'Deleted By Admin')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='periodictourregistration',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Confirmed', 'Active', 'Cancelled_By_Owner', 'Cancelled_By_Guest', 'Completed', 'Deleted_By_Admin'])), name='chk_tour_reg_status'),
        ),
    ]
