# Generated by Django 5.0.2 on 2024-03-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touristicagencies', '0004_alter_tour_end_date_alter_tour_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
