# Generated by Django 5.0.2 on 2024-05-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristicagencies', '0005_remove_periodictourregistration_chk_tour_reg_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictour',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='tourism_agencies/periodic_tours/'),
        ),
        migrations.AlterField(
            model_name='touristicagency',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='tourism_agencies/agencies/'),
        ),
    ]
