# Generated by Django 5.0.2 on 2024-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_country_iso'),
        ('guests', '0008_guest_status_guest_chk_guest_status'),
        ('touristicagencies', '0006_alter_periodictour_cover_img_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodictourregistration',
            name='chk_tour_reg_status',
        ),
        migrations.AlterField(
            model_name='periodictourregistration',
            name='status',
            field=models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Confirmed', 'Confirmed'), ('Active', 'Active'), ('Cancelled By Owner', 'Cancelled By Owner'), ('Cancelled By Guest', 'Cancelled By Guest'), ('Completed', 'Completed'), ('Deleted_By_Admin', 'Deleted By Admin')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='periodictourregistration',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Uncompleted', 'Confirmed', 'Active', 'Cancelled By Owner', 'Cancelled By Guest', 'Completed', 'Deleted_By_Admin'])), name='chk_tour_reg_status'),
        ),
    ]
