# Generated by Django 5.0.2 on 2024-05-20 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristicagencies', '0007_remove_periodictourregistration_chk_tour_reg_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictour',
            name='price',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(regex='^\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='periodictourregistration',
            name='phone',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(regex='^\\d{7,15}$')]),
        ),
    ]
