# Generated by Django 5.0.2 on 2024-04-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='destinations.country'),
        ),
    ]
