# Generated by Django 5.0.2 on 2024-03-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.URLField(null=True),
        ),
    ]
