# Generated by Django 5.0.2 on 2024-05-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_city_cover_img_alter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='destinations/cities/'),
        ),
    ]
