# Generated by Django 5.0.2 on 2024-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_city_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityimage',
            name='image',
            field=models.ImageField(upload_to='destinations/cities/'),
        ),
    ]
