# Generated by Django 5.0.2 on 2024-04-19 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_city_description_country_country_code_and_more'),
        ('guests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='country_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='destinations.country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.PositiveIntegerField(max_length=15, null=True),
        ),
    ]
