# Generated by Django 5.0.2 on 2024-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
