# Generated by Django 5.0.2 on 2024-04-19 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_country_code_alter_guest_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7,15}$')]),
        ),
    ]
