# Generated by Django 5.0.2 on 2024-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='guests/'),
        ),
    ]
