# Generated by Django 5.0.2 on 2024-05-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_guest_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
