# Generated by Django 5.0.2 on 2024-05-18 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_country_iso'),
        ('guests', '0007_guest_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Banned', 'Banned'), ('Deleted By User', 'Deleted By User'), ('Deleted By Admin', 'Deleted By Admin')], default='Active', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Active', 'Banned', 'Deleted By User', 'Deleted By Admin'])), name='chk_guest_status'),
        ),
    ]
