# Generated by Django 5.0.2 on 2024-05-20 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_guest_status_guest_chk_guest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7,15}$')]),
        ),
    ]
