# Generated by Django 5.0.2 on 2024-03-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
    ]
