# Generated by Django 5.0.2 on 2024-05-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='is_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
