# Generated by Django 5.0.2 on 2024-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetcode_is_token_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='id_pic',
            field=models.ImageField(upload_to='users/identities/'),
        ),
    ]
