# Generated by Django 5.0.2 on 2024-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_confirmationcode_passwordresetcode_delete_activation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='token',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='token',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
