# Generated by Django 5.0.2 on 2024-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_owner_country_code_alter_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='birthday',
            field=models.DateField(auto_now=True),
        ),
    ]
