# Generated by Django 5.0.2 on 2024-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_owner_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='owners/'),
        ),
    ]
