# Generated by Django 5.0.2 on 2024-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_owner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
