# Generated by Django 5.0.2 on 2024-05-20 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0008_owner_status_owner_chk_owner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(regex='^\\d{7,15}$')]),
        ),
    ]
