# Generated by Django 5.0.2 on 2024-05-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0009_alter_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
